name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_app.py -v

      - name: Test multiply function directly
        run: |
          python -c "from app import multiply; assert multiply(3, 4) == 12; print('✅ Test passed: multiply(3, 4) == 12')"

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t python-multiply-app .

      - name: Test Docker container
        run: |
          docker run --rm python-multiply-app python -c "from app import multiply; assert multiply(3, 4) == 12; print('✅ Docker test passed')"
